# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JGLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='\u7f16\u7801')),
                ('text', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archives.JGLB')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u7c7b\u522b',
                'verbose_name_plural': '\u673a\u6784\u7c7b\u522b',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JGLSCJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='\u7f16\u7801')),
                ('text', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('parent_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='\u4e0a\u7ea7\u7f16\u7801')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7',
                'verbose_name_plural': '\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='JGXZJB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='\u7f16\u7801')),
                ('text', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('parent_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='\u4e0a\u7ea7\u7f16\u7801')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u884c\u653f\u7ea7\u522b',
                'verbose_name_plural': '\u673a\u6784\u884c\u653f\u7ea7\u522b',
            },
        ),
        migrations.CreateModel(
            name='SFXZJGJBXX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JGBM', models.CharField(max_length=18, verbose_name='\u673a\u6784\u7f16\u7801')),
                ('JGMC', models.CharField(max_length=60, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('JGJC', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u673a\u6784\u7b80\u79f0')),
                ('YWMC', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('JGDM', models.CharField(max_length=20, verbose_name='\u673a\u6784\u4ee3\u7801')),
                ('FZR', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('LXDH', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('CZHM', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u4f20\u771f\u53f7\u7801')),
                ('DZYX', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('YB', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u90ae\u7f16')),
                ('DZ', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5730\u5740')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('JGLB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.JGLB', verbose_name='\u673a\u6784\u7c7b\u522b')),
                ('JGLSCJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.JGLSCJ', verbose_name='\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7')),
                ('JGXZJB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.JGXZJB', verbose_name='\u673a\u6784\u884c\u653f\u7ea7\u522b')),
                ('SJSFXZZGBM', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sjsfxzzgbm_children', to='archives.SFXZJGJBXX')),
                ('SJSFXZZGJG', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sjsfxzzgjg_children', to='archives.SFXZJGJBXX')),
            ],
            options={
                'verbose_name': '\u53f8\u6cd5\u884c\u653f\u673a\u5173\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u53f8\u6cd5\u884c\u653f\u673a\u5173\u57fa\u672c\u4fe1\u606f',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='XZQH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='\u7f16\u7801')),
                ('text', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archives.XZQH')),
            ],
            options={
                'verbose_name': '\u884c\u653f\u533a\u5212',
                'verbose_name_plural': '\u884c\u653f\u533a\u5212',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
