# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JGLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('text', models.CharField(max_length=20)),
                ('parent_code', models.CharField(max_length=4)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JGLSCJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=20)),
                ('parent_code', models.CharField(max_length=2)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JGXZJB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=20)),
                ('parent_code', models.CharField(max_length=2)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SFXZJGJBXX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JGBM', models.CharField(max_length=16)),
                ('JGMC', models.CharField(max_length=60)),
                ('JGJC', models.CharField(max_length=60)),
                ('YWMC', models.CharField(max_length=60)),
                ('JGDM', models.CharField(max_length=20)),
                ('FZR', models.CharField(max_length=20)),
                ('JGLB', models.CharField(max_length=4)),
                ('JGXZJB', models.CharField(max_length=2)),
                ('JGLSCJ', models.CharField(max_length=2)),
                ('SJSFXZZGJG', models.CharField(max_length=16)),
                ('SJSFXZZGBM', models.CharField(max_length=16)),
                ('LXDH', models.CharField(max_length=40)),
                ('CZHM', models.CharField(max_length=40)),
                ('DZYX', models.CharField(max_length=60)),
                ('YB', models.CharField(max_length=6)),
                ('DZ', models.CharField(max_length=200)),
            ],
        ),
    ]
