# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20160420_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jglb',
            options={'verbose_name': '\u673a\u6784\u7c7b\u522b', 'verbose_name_plural': '\u673a\u6784\u7c7b\u522b'},
        ),
        migrations.AlterModelOptions(
            name='jglscj',
            options={'verbose_name': '\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7', 'verbose_name_plural': '\u673a\u6784\u96b6\u5fc5\u5c42\u7ea7'},
        ),
        migrations.AlterModelOptions(
            name='jgxzjb',
            options={'verbose_name': '\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7', 'verbose_name_plural': '\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7'},
        ),
        migrations.AlterModelOptions(
            name='sfxzjgjbxx',
            options={'verbose_name': '\u53f8\u6cd5\u884c\u653f\u673a\u5173\u57fa\u672c\u4fe1\u606f', 'verbose_name_plural': '\u53f8\u6cd5\u884c\u653f\u673a\u5173\u57fa\u672c\u4fe1\u606f'},
        ),
        migrations.RemoveField(
            model_name='jglb',
            name='parent_code',
        ),
        migrations.AlterField(
            model_name='jglb',
            name='code',
            field=models.CharField(max_length=4, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='jglb',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='jglb',
            name='text',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jglscj',
            name='code',
            field=models.CharField(max_length=2, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='jglscj',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='jglscj',
            name='parent_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='\u4e0a\u7ea7\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='jglscj',
            name='text',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jgxzjb',
            name='code',
            field=models.CharField(max_length=2, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='jgxzjb',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='jgxzjb',
            name='parent_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='\u4e0a\u7ea7\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='jgxzjb',
            name='text',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='CZHM',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u4f20\u771f\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='DZ',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='DZYX',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='FZR',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGBM',
            field=models.CharField(max_length=16, verbose_name='\u673a\u6784\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGDM',
            field=models.CharField(max_length=20, verbose_name='\u673a\u6784\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGJC',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u673a\u6784\u7b80\u79f0'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGLB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.JGLB', verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGLSCJ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.JGLSCJ', verbose_name='\u673a\u6784\u96b6\u5c5e\u5c42\u7ea7'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGMC',
            field=models.CharField(max_length=60, verbose_name='\u673a\u6784\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='JGXZJB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.JGXZJB', verbose_name='\u673a\u6784\u884c\u653f\u7ea7\u522b'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='LXDH',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='SJSFXZZGBM',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4e0a\u7ea7\u53f8\u6cd5\u884c\u653f\u4e3b\u7ba1\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='SJSFXZZGJG',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4e0a\u7ea7\u53f8\u6cd5\u884c\u653f\u4e3b\u7ba1\u673a\u5173'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='YB',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='\u90ae\u7f16'),
        ),
        migrations.AlterField(
            model_name='sfxzjgjbxx',
            name='YWMC',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u82f1\u6587\u540d\u79f0'),
        ),
    ]
